---
title: "Rmd Presentation & Plotly"
author: "Ceci Practice"
date: "2024/5/17"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Slide with Bullets

- Plotly Plot Example

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r plotfig}
library(plotly)

data <- data.frame(
  x = rep(1:10, 3),
  y = c(10, 15, 13, 17, 19, 21, 25, 22, 23, 24,
        12, 18, 16, 14, 20, 22, 21, 19, 25, 27,
        14, 17, 15, 20, 22, 24, 23, 21, 26, 28),
  group = rep(c("A", "B", "C"), each = 10)
)

fig1 <- plot_ly(data, x = ~x, y = ~y, color = ~group, type = 'scatter', mode = 'lines+markers') %>%
  layout(title = "Line Graph",
         xaxis = list(title = "X"),
         yaxis = list(title = "Y"))

fig1



set.seed(123)
data3d <- data.frame(
  x = rnorm(100),
  y = rnorm(100),
  z = rnorm(100),
  color = sample(1:3, 100, replace = TRUE)
)


fig2 <- plot_ly(data3d, x = ~x, y = ~y, z = ~z, color = ~as.factor(color), type = 'scatter3d', mode = 'markers') %>%
  layout(title = "3D dot graph",
         scene = list(
           xaxis = list(title = "X"),
           yaxis = list(title = "Y"),
           zaxis = list(title = "Z")
         ))


fig2


```

